### ISSUE TITLE
Directly Open Browser without Login

### ISSUE THREAD

**Issue by pratham1002** [utkrixx/Hangouts_Meet_Automation#3]
It might be possible to replace the `gmail_login()` function with a simpler version
```python
import webbrowser
webbrowser.open('https://meet.google.com/abc-efgh-ijk?authuser=1')
```
and then proceed on to turn off the mic, camera and joining the meet.

Why?
It could avoid running into recaptcha while logging in.

PS - Any ideas for screen recording the newly opened chrome tab?

**Comment by utkrix** [comment]
When I ran it, i couldn't sign in into my meet because Chromium detected that it is an automated script and so I first logged into gmail and within 2 seconds went to meet. 
About screen recording, I'm sorry, I am not much familiar with this. I use simple screen recorder for Linux to record my screen.
